### ISSUE TITLE
Install Non preview versions

### ISSUE THREAD

**Issue by Stephanevg** [jdhitsolutions/PSReleaseTools#11]
Hi @jdhitsolutions 

Does this module supoprts the installation of non preview versions of PowerShell?
If not, it could be an interesting feature to have (like, with a silent installer etc..).

**Comment by jdhitsolutions** [comment]
I don't have any code that automatically installs standard versions.  But it wouldn't be that hard to save an asset and install it.

```powershell
msiexec (Get-PSReleaseAsset -Family Windows -Format msi -Only64Bit | Save-PSReleaseAsset -Path $env:temp -Passthru).FullName /quiet
```

**Comment by Stephanevg** [comment]
Yeah, to me it would make sense to wrap in a function, and add it as default feature of this module.
Afterall, the install functionality is there for PreReleases ;)

I think it could ease how people install powershell on machines, and how it is deployed in Enterprises for example.

**Comment by jdhitsolutions** [comment]
I could do that, but I would only do it for Windows platforms using the MSI.

**Comment by Stephanevg** [comment]
Yeah, that would be fine for me.
But I would still recommend to leave a door open for extending it to other platforms. 

It would be a real benefit I think

**Comment by jdhitsolutions** [comment]
I added a command in v1.2.0 to install the stable PowerShell Core. I am going to focus on Windows platforms only. Other platforms have existing install tools and there's no way I can develop and test installation commands for all of them.

**Comment by jdhitsolutions** [comment]
Added a windows-only command to install the standard PSCore.
