### ISSUE TITLE
Not Testable on OSX

### ISSUE THREAD

**Issue by johnmccrae** [jdhitsolutions/PSReleaseTools#2]
This looks really exciting but currently not testable on OSX - the latest Alpha on OSX still tells me that PSGallery Is Currently Unavailable.  UGH. Set-PSRepository isn't working correctly.

**Comment by jdhitsolutions** [comment]
Hmm. I had someone test this on the Mac and he said it worked. Let me double check.

**Comment by jdhitsolutions** [comment]
Just realized, we're talking about two different things. As far as I know the commands in my module will work on a Mac once you get it installed. *Using* the gallery is something completely different. Having another Mac user test for me.

**Comment by jdhitsolutions** [comment]
So I have verified with 2 other Mac users that you should be able to run Find-Module and Install-Module on the Mac. To install you will need to run:
```
install-module psreleasetools -scope CurrentUser
```

**Comment by gitdave225** [comment]
Had to install PS 6 alpha 15 before the find-module and install-module commands even worked for me. Once that was done, I ran the install-module psreleasetools -scope CurrentUser and had this working.

**Comment by johnmccrae** [comment]
Thanks very much!
