### ISSUE TITLE
Bug: If no MSI is available (only zip) Install-PSPreview fails

### ISSUE THREAD

**Issue by mortenlerudjordet** [jdhitsolutions/PSReleaseTools#21]
### PSVersion Table

PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### What is the syntax or expression you are using?
Install-PSPreview -mode passive

### What happens?
Error: 
InstallMsi : Cannot validate argument on parameter 'Path'. Cannot bind argument to parameter 'Path' because it is an em
pty string.
C:\Program Files\WindowsPowerShell\Modules\PSReleaseTools\1.6.1\functions\public.ps1:414 char:28

### What do you think should happen?
I tracked down the problem to the line : Get-PSReleaseAsset -Preview -Family Windows -Only64Bit -Format msi
At the time of testing I tried to install PS 7.1.0 preview 4, though it seems there are no msi available on the site.
Therefore this strange error is thrown.

**Comment by jdhitsolutions** [comment]
Thanks for reporting. I'll take a look.

**Comment by jdhitsolutions** [comment]
I'm checking with Microsoft to see if this is merely an omission or a change in direction.

**Comment by mortenlerudjordet** [comment]
They have a bug on their side i think when it comes to the MSI.

Note: MSI installer packages have been removed due to #13035 till further investigation.
https://github.com/PowerShell/PowerShell/releases/tag/v7.1.0-preview.4

**Comment by jdhitsolutions** [comment]
That would explain it. I doubt I'll change the install command since it relies on an MSI file. The zip file can already be downloaded using `Save-PSReleaseAsset`.

**Comment by mortenlerudjordet** [comment]
Was thinking of adding a more descriptive error message?

**Comment by jdhitsolutions** [comment]
I suppose I could update the warning message.

**Comment by jdhitsolutions** [comment]
I've pushed v1.6.2 to the PowerShell Gallery with (hopefully) improved warning messages.

```text
PS C:\> install-pspreview
WARNING: Get-PSReleaseAsset Failed to find any release assets using the specified critiera.
WARNING: No preview MSI file found to download and install.
```

And dang it, I have a typo.

**Comment by mortenlerudjordet** [comment]
I like it:
WARNING: Get-PSReleaseAsset Failed to find any release asse
WARNING: No preview MSI file found to download and install.

Closing
