### ISSUE TITLE
Dead link for `help Install-PowerShell -Online`

### ISSUE THREAD

**Issue by albers** [jdhitsolutions/PSReleaseTools#25]
### PSVersion Table
```text
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### What is the syntax or expression you are using?
`help Install-PowerShell -Online`

### What happens?
The url http://bit.ly/325i1Bm is opened and the redirected to https://github.com/jdhitsolutions/PSReleaseTools/blob/master/Docs/Install-PSCore.md , which does not exist.  The default 404 error page of GitHub is shown.

### What do you think should happen?
The redirect should point to https://github.com/jdhitsolutions/PSReleaseTools/blob/master/Docs/Install-PowerShell.md

**Comment by jdhitsolutions** [comment]
Well, that is sub-optimal.

**Comment by jdhitsolutions** [comment]
Guessed I missed this when I re-organized the module. I will have to generate a new bitly link, update the source files, and re-publish the module.

**Comment by jdhitsolutions** [comment]
I had a pending update so I was able to fix this issue. Update the module to v1.10.0 and see if this works better.

**Comment by albers** [comment]
I can confirm the issue is no longer present in 1.10.0. Thanks for the quick fix.
