### ISSUE TITLE
Updating Windows Terminal Reference?

### ISSUE THREAD

**Issue by markolbert** [jdhitsolutions/PSReleaseTools#26]
Quick question: I installed the tools and did an install to upgrade from 7.1.3 to 7.1.4 (which worked perfectly). But I'm still getting the nag announcement every time I launch Windows Terminal (i.e., Terminal doesn't seem to recognize the update). Is there a way to fix that with the tools?

**Comment by jdhitsolutions** [comment]
So when you open PowerShell in Windows Terminal you see the nag notice? Does it happen in the traditional console. Not sure if this is a PowerShell issue or something with Windows Terminal. You are supposed to be able to put a line like this in your profile script to disable the nag prompts.

```powershell
$Env:POWERSHELL_UPDATECHECK = 'Off'
```

You might also just re-install Windows Terminal. I had something odd in Windows Terminal the other day where it wasn't detected even though I was in it. I updated/re-installed Windows Terminal and that seemed to help. Certainly won't hurt anything.
