### ISSUE TITLE
Get preview releases

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSReleaseTools#7]
Currently, this module defaults to getting stable releases. Need to add parameter options to get preview builds.

**Comment by mavaddat** [comment]
Here is my attempt to solve this: https://github.com/jdhitsolutions/PSReleaseTools/pull/8

**Comment by jdhitsolutions** [comment]
Install the latest version from the PowerShell Gallery. You'll now see a -Preview parameter that works. I added this in v0.8.0
